# export FIRST_GOPATH=$HOME/go
# export CODIES_DIR=$FIRST_GOPATH/src/github.com/CodiesTeam/codies-server
codies-server:
  image: golang:1.7.5-alpine
  working_dir: /go/src/github.com/CodiesTeam/codies-server
  command: go run cmd/livereload/main.go -watch=server -o=server -e=vendor,Godeps,docker,cmd
  volumes:
    - $CODIES_DIR:/go/src/github.com/CodiesTeam/codies-server
  ports:
    - 8888:8888
  links:
    - redis
    - postgre

redis:
  image: redis:3.2-alpine
  ports:
    - 6377:6379

postgre:
  image: postgres:9.2-alpine
  volumes:
    - $CODIES_DIR/docker/volumes/postgre:/var/lib/postgresql/data
  ports:
    - 5432:5432
  environment:
    POSTGRES_PASSWORD: postgre